# Generated by Django 2.1.1 on 2018-09-10 06:03

import comments.export
import comments.models
import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=core.utils.OverwriteStorage(), upload_to='export')),
                ('status', models.PositiveIntegerField(choices=[(1, comments.models.Status(1)), (2, comments.models.Status(2)), (3, comments.models.Status(3)), (4, comments.models.Status(4))], db_index=True, default=comments.models.Status(1))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(choices=[('xml', comments.export.Format('xml')), ('json', comments.export.Format('json'))], max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
